version: "3.9"

services:

  ghost:
    image: ghost
    ports:
      - "2368:2368"
    volumes:
      - content:/var/lib/ghost/content

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:1234"
      - "1235:1235"

volumes:
  content: {}
